### ISSUE TITLE
Tag new version with changes from the INN import

### ISSUE THREAD

**Issue by benlk** [nprds/nprapi-wordpress#23]
The tag name should be either `v1.5.3` or `v1.6`.

Things that will need to be updated before tagging a release and running `release.sh`:

- [ ] README.md
- [ ] ds-npr-api.php
- [ ] readme.txt, both in version number and release notes

After all necessary documentation is updated, the repo should be `git tagged` with the new tag name, and a [GitHub release note](https://help.github.com/articles/creating-releases/) should be written and applied to this repository.

**Comment by aschweigert** [comment]
given the size of this change, i'd say 1.6 makes most sense, what do you think, @mike-douglas?

**Comment by mike-douglas** [comment]
`v1.6` makes sense to me, I can create the tag and update things as needed (I'm also working on the image assets for icon/banner).

Would you guys be able to sum up in a bulleted list the changes that were made for this release? I could be general about it, but I know a lot was done and honestly I'm starting to lose my context between the three other plugins we're also working on. It would help a ton.

**Comment by benlk** [comment]
User-facing changes:

- Add meta box to post edit page to explicitly push a story to NPR One
- Add [documentation](https://github.com/nprds/nprapi-wordpress/tree/master/docs)
- If pushing a story to NPR fails, the error message is displayed on the post edit page
- If it succeeds, a success message is displayed
- Rename the plugin to "NPR Story API"
- The plugin now requires certain WordPress capabilities before performing API actions:
    - deleting posts in the API now requires the `delete_others_posts` capability for the user trying to delete the post. In effect, this limits deletion of stories from the NPR API to admins and editors.
    - pushing stories to the API requires the `publish_posts` capability, which means that contributors and guests can't push to NPR.
    - pulling posts from the API requires the `edit_posts` capability, meaning that contributors and guests can't pull from NPR. We may want to revisit this in the future, or make the permissions filterable if sites using the plugin want to lock permissions down or open them up.
- A number of settings in the admin now use the `number` input type instead of text fields

Developer-facing changes:

- Added unit tests for much of the PHP code
- Most functions were renamed to use the prefix `nprstory_` instead of `ds_npr_` or no common prefix. This does not affect
- Added nonces, input sanitization, and input validation for settings.
- `DS_NPR_API` class now uses new-style `__construct()` constructor.
- Removed `/wp-admin/includes/admin.php`, `/wp-load.php`, `/wp-includes/class-wp-error.php` from the cron job function, see https://github.com/nprds/nprapi-wordpress/pull/19/commits/4b3d65a19122b0da5215997939db94c7accf3e5e and https://github.com/nprds/nprapi-wordpress/pull/19/commits/cf2dfa39c1f118d0ca0c836d7967e09baec63bd6 - the cron job works without them.

I think that's everything major.

**Comment by benlk** [comment]
1.6 is [tagged](https://github.com/nprds/nprapi-wordpress/releases/tag/1.6) and was released on the wordpress.org plugins repo.
