### ISSUE TITLE
Plugin needs thumbnail, banner assets for WordPress.org plugin repository

### ISSUE THREAD

**Issue by benlk** [nprds/nprapi-wordpress#24]
Information on icon sizes and formats: https://make.wordpress.org/core/2014/08/21/introducing-plugin-icons-in-the-plugin-installer/

Information on banner sizes and formats: https://wordpress.org/plugins/about/faq/#banners

To push these items to the WordPress.org repository, follow the instructions for release .sh under ["Updating the assets/ directory of svn/"](https://github.com/INN/docs/blob/master/projects/wordpress-plugins/release.sh.md#updating-the-assets-directory-of-svn).

Because the assets are stored independently of the source code of the plugin, this does *not* require tagging a new release in GitHub, or even making a commit in git. I'm putting this task here just so it's written down someplace.

**Comment by mike-douglas** [comment]
Done!
